let colors = generateColorsArray(6);

// Getting all squares to assign RGB values to each by index  
let squares = document.querySelectorAll(".square");
let selectedColor = chooseGameColor(colors);
let displayColor = document.querySelector("#displayColor");
let message = document.querySelector("#message");

// Display the selected color value to the page header/title
displayColor.textContent = selectedColor;

for (let i = 0; i < squares.length; i++) {
    squares[i].style.backgroundColor = colors[i];

    squares[i].addEventListener("click", function () {
        if (this.style.backgroundColor === displayColor.textContent) {
            message.textContent = "Correct!";
            changeAllToSpecificColor(selectedColor);
        } else {
            this.style.backgroundColor = "#232323";
            message.textContent = "Wrong! Try Again!";
        }
    });
}

function changeAllToSpecificColor(color) {
    for (let i = 0; i < squares.length; i++) {
        squares[i].style.backgroundColor = color;
    }
}

// Function choses a random color from the array for the current round of the game 
function chooseGameColor(colorsArray) {
    // returns random number between 0 and colorsaArray.length-1
    let index = Math.floor(Math.random() * colorsArray.length);
    return colorsArray[index];
}

// Function returns an array of colors with size === number
function generateColorsArray(number) {
    let colorsArray = [];
    for (let i = 0; i < number; i++) {
        colorsArray.push(generateRandomColor());
    }
    return colorsArray;
}

// Function returns a random string of rgb values 
function generateRandomColor() {
    // Random color is generated by picking R G B values between 0 and 225
    let r = Math.floor(Math.random() * 256);
    let g = Math.floor(Math.random() * 256);
    let b = Math.floor(Math.random() * 256);
    return "rgb(" + r + ", " + g + ", " + b + ")";
}